### ISSUE TITLE
`prepare_mapping_pipeline:downloadGenome` declares 2 input channels but 1 were specified

### ISSUE THREAD

**Issue by zhaoshuoxp** [pinellolab/CRISPR_Pipeline#1]
Hi, this is Quanyi from characterization group, I am trying to run the pipeline with TF_Perturb_Seq_Pilot Dataset.  However I got this error message when running with nextflow run main.nf -c input.config :

Dec-20 10:28:54.283 [main] DEBUG nextflow.Session - Session aborted -- Cause: Process `prepare_mapping_pipeline:downloadGenome` declares 2 input channels but 1 were specified

looks like a setup issue in the config file. do you have any idea on this? Thanks

------full .nextflow.log------
Dec-20 10:28:50.075 [main] DEBUG nextflow.cli.Launcher - $> nextflow run main.nf -c input.config
Dec-20 10:28:50.177 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 23.10.1
Dec-20 10:28:50.201 [main] DEBUG nextflow.plugin.PluginsFacade - Setting up plugin manager > mode=prod; embedded=false; plugins-dir=/home/quanyiz/.nextflow/plugins; core-plugins: nf-amazon@2.1.4,nf-azure@1.3.3,nf-cloudcache@0.3.0,nf-codecommit@0.1.5,nf-console@1.0.6,nf-ga4gh@1.1.0,nf-google@1.8.3,nf-tower@1.6.3,nf-wave@1.0.1
Dec-20 10:28:50.214 [main] INFO  o.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Dec-20 10:28:50.215 [main] INFO  o.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Dec-20 10:28:50.219 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.4.1 in 'deployment' mode
Dec-20 10:28:50.230 [main] INFO  org.pf4j.AbstractPluginManager - No plugins
Dec-20 10:28:50.256 [main] DEBUG nextflow.config.ConfigBuilder - User config file: /nfs/baldar/quanyiz/app/CRISPR_Pipeline/input.config
Dec-20 10:28:50.256 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /nfs/baldar/quanyiz/app/CRISPR_Pipeline/input.config
Dec-20 10:28:50.282 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `standard`
Dec-20 10:28:51.202 [main] DEBUG nextflow.cli.CmdRun - Applied DSL=2 from script declararion
Dec-20 10:28:51.225 [main] INFO  nextflow.cli.CmdRun - Launching `main.nf` [maniac_marconi] DSL2 - revision: 79916babfe
Dec-20 10:28:51.226 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins default=[]
Dec-20 10:28:51.226 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins resolved requirement=[]
Dec-20 10:28:51.238 [main] DEBUG n.secret.LocalSecretsProvider - Secrets store: /home/quanyiz/.nextflow/secrets/store.json
Dec-20 10:28:51.242 [main] DEBUG nextflow.secret.SecretsLoader - Discovered secrets providers: [nextflow.secret.LocalSecretsProvider@178f268a] - activable => nextflow.secret.LocalSecretsProvider@178f268a
Dec-20 10:28:51.306 [main] DEBUG nextflow.Session - Session UUID: bd431bc5-4bf0-4cdb-a1fb-a1917f907c81
Dec-20 10:28:51.306 [main] DEBUG nextflow.Session - Run name: maniac_marconi
Dec-20 10:28:51.307 [main] DEBUG nextflow.Session - Executor pool size: 160
Dec-20 10:28:51.314 [main] DEBUG nextflow.file.FilePorter - File porter settings maxRetries=3; maxTransfers=50; pollTimeout=null
Dec-20 10:28:51.319 [main] DEBUG nextflow.util.ThreadPoolBuilder - Creating thread pool 'FileTransfer' minSize=10; maxSize=480; workQueue=LinkedBlockingQueue[10000]; allowCoreThreadTimeout=false
Dec-20 10:28:51.351 [main] DEBUG nextflow.cli.CmdRun -
  Version: 23.10.1 build 5891
  Created: 12-01-2024 22:01 UTC (14:01 PDT)
  System: Linux 5.4.0-182-generic
  Runtime: Groovy 3.0.19 on OpenJDK 64-Bit Server VM 17.0.11+9-Ubuntu-120.04.2
  Encoding: UTF-8 (UTF-8)
  Process: 2546789@THOR-cvmed [127.0.1.1]
  CPUs: 160 - Mem: 1.5 TB (18.8 GB) - Swap: 100 GB (607 MB)
Dec-20 10:28:51.394 [main] DEBUG nextflow.Session - Work-dir: /nfs/baldar/quanyiz/app/CRISPR_Pipeline/work [nfs]
Dec-20 10:28:51.422 [main] DEBUG nextflow.executor.ExecutorFactory - Extension executors providers=[]
Dec-20 10:28:51.432 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Dec-20 10:28:51.471 [main] DEBUG nextflow.cache.CacheFactory - Using Nextflow cache factory: nextflow.cache.DefaultCacheFactory
Dec-20 10:28:51.481 [main] DEBUG nextflow.util.CustomThreadPool - Creating default thread pool > poolSize: 161; maxThreads: 1000
Dec-20 10:28:51.587 [main] DEBUG nextflow.Session - Session start
Dec-20 10:28:51.821 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Dec-20 10:28:54.189 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withName:seqSpecCheck` matches process seqSpecCheck_pipeline_HASHING:guideWorkflow:seqSpecCheck
Dec-20 10:28:54.196 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Dec-20 10:28:54.196 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Dec-20 10:28:54.203 [main] DEBUG nextflow.executor.Executor - [warm up] executor > local
Dec-20 10:28:54.209 [main] DEBUG n.processor.LocalPollingMonitor - Creating local task monitor for executor 'local' > cpus=160; memory=1.5 TB; capacity=160; pollInterval=100ms; dumpInterval=5m
Dec-20 10:28:54.211 [main] DEBUG n.processor.TaskPollingMonitor - >>> barrier register (monitor: local)
Dec-20 10:28:54.271 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withName:seqSpecCheck` matches process seqSpecCheck_pipeline_HASHING:hashingWorkflow:seqSpecCheck
Dec-20 10:28:54.273 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Dec-20 10:28:54.273 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Dec-20 10:28:54.283 [main] DEBUG nextflow.script.ScriptRunner - Parsed script files:
  Script_150c86d83d41a089: /nfs/baldar/quanyiz/app/CRISPR_Pipeline/././processes/downloadReference.nf
  Script_205e74ddad45bba2: /nfs/baldar/quanyiz/app/CRISPR_Pipeline/././processes/skipGenomeDownload.nf
  Script_f3e18d6a60d747a8: /nfs/baldar/quanyiz/app/CRISPR_Pipeline/././processes/prepare_covariate.nf
  Script_0e369ff81e884a44: /nfs/baldar/quanyiz/app/CRISPR_Pipeline/././processes/anndata_concat.nf
  Script_a7ddf0724e06c9b1: /nfs/baldar/quanyiz/app/CRISPR_Pipeline/././processes/mappingHashing.nf
  Script_1533b67efe3721da: /nfs/baldar/quanyiz/app/CRISPR_Pipeline/././processes/prepare_guide_inference.nf
  Script_6f1ead8d77767824: /nfs/baldar/quanyiz/app/CRISPR_Pipeline/././processes/CreateMuData_HASHING.nf
  Script_8092fba704e0b7c7: /nfs/baldar/quanyiz/app/CRISPR_Pipeline/././processes/createHashingRef.nf
  Script_dabf5e668019cb7c: /nfs/baldar/quanyiz/app/CRISPR_Pipeline/./process_mudata_pipeline_HASHING.nf
  Script_7894984b1822b41b: /nfs/baldar/quanyiz/app/CRISPR_Pipeline/././processes/filter_hashing.nf
  Script_df40e8197306806c: /nfs/baldar/quanyiz/app/CRISPR_Pipeline/././processes/evaluation_plot.nf
  Script_85389858d5d1ca37: /nfs/baldar/quanyiz/app/CRISPR_Pipeline/././processes/inference_mudata.nf
  Script_331c1557ebd979d3: /nfs/baldar/quanyiz/app/CRISPR_Pipeline/././processes/CreateMuData.nf
  Script_6ae22a4d1f97a674: /nfs/baldar/quanyiz/app/CRISPR_Pipeline/./evaluation_pipeline.nf
  Script_95d7670a091c52ca: /nfs/baldar/quanyiz/app/CRISPR_Pipeline/././processes/seqSpecParser.nf
  Script_364a341b1533bc75: /nfs/baldar/quanyiz/app/CRISPR_Pipeline/././processes/doublets_scrub.nf
  Script_18a032aecf31d801: /nfs/baldar/quanyiz/app/CRISPR_Pipeline/./seqSpecCheck_pipeline.nf
  Script_80a2e89f94bdd102: /nfs/baldar/quanyiz/app/CRISPR_Pipeline/././processes/inference_sceptre.nf
  Script_2485bcf195aa84d1: /nfs/baldar/quanyiz/app/CRISPR_Pipeline/././processes/evaluation_undefined_plot.nf
  Script_89dc5f2cfc8533ea: /nfs/baldar/quanyiz/app/CRISPR_Pipeline/./process_mudata_pipeline.nf
  Script_040370fc51e1482e: /nfs/baldar/quanyiz/app/CRISPR_Pipeline/././processes/prepare_user_guide_inference.nf
  Script_f0134e74d2f70b55: /nfs/baldar/quanyiz/app/CRISPR_Pipeline/././processes/prepare_all_guide_inference.nf
  Script_caee67b3b3a2cb25: /nfs/baldar/quanyiz/app/CRISPR_Pipeline/././processes/doublets_scrub_HASHING.nf
  Script_4f9348f25ad165ce: /nfs/baldar/quanyiz/app/CRISPR_Pipeline/././processes/hashing_concat.nf
  Script_b610b7f143b9598e: /nfs/baldar/quanyiz/app/CRISPR_Pipeline/./seqSpecCheck_pipeline_HASHING.nf
  Script_2b701941c560385a: /nfs/baldar/quanyiz/app/CRISPR_Pipeline/./dashboard_pipeline_HASHING.nf
  Script_e56a3dae70b96ab5: /nfs/baldar/quanyiz/app/CRISPR_Pipeline/././processes/mappingGuide.nf
  Script_7a541110402dceee: /nfs/baldar/quanyiz/app/CRISPR_Pipeline/main.nf
  Script_1bf0df2541760431: /nfs/baldar/quanyiz/app/CRISPR_Pipeline/./dashboard_pipeline.nf
  Script_13e5d248ad1ff388: /nfs/baldar/quanyiz/app/CRISPR_Pipeline/./prepare_mapping_pipeline.nf
  Script_233e20384ac69b6a: /nfs/baldar/quanyiz/app/CRISPR_Pipeline/././processes/guide_assignment_mudata.nf
  Script_148ca85f24672b01: /nfs/baldar/quanyiz/app/CRISPR_Pipeline/././processes/dashboard_HASHING.nf
  Script_504001d5182f9449: /nfs/baldar/quanyiz/app/CRISPR_Pipeline/././processes/downloadGTF.nf
  Script_c887b3a4b6ec58c9: /nfs/baldar/quanyiz/app/CRISPR_Pipeline/./mapping_rna_pipeline.nf
  Script_c77bcba19d2c8346: /nfs/baldar/quanyiz/app/CRISPR_Pipeline/././processes/guide_assignment_sceptre.nf
  Script_a2f0520374ea6364: /nfs/baldar/quanyiz/app/CRISPR_Pipeline/././processes/mappingscRNA.nf
  Script_89460474fd8a823c: /nfs/baldar/quanyiz/app/CRISPR_Pipeline/././processes/guide_assignment_cleanser.nf
  Script_35f3693fb282f079: /nfs/baldar/quanyiz/app/CRISPR_Pipeline/././processes/createGuideRef.nf
  Script_6cb51f2aca15406f: /nfs/baldar/quanyiz/app/CRISPR_Pipeline/././processes/demultiplex.nf
  Script_37bf8488190eb1e3: /nfs/baldar/quanyiz/app/CRISPR_Pipeline/././processes/dashboard.nf
  Script_a382cc6ea65db7ec: /nfs/baldar/quanyiz/app/CRISPR_Pipeline/./mapping_hashing_pipeline.nf
  Script_5e25f067688af577: /nfs/baldar/quanyiz/app/CRISPR_Pipeline/././processes/PreprocessAnnData.nf
  Script_1792d4ef0ebf177a: /nfs/baldar/quanyiz/app/CRISPR_Pipeline/././processes/downloadGenome.nf
  Script_d4a922d818e7356b: /nfs/baldar/quanyiz/app/CRISPR_Pipeline/././processes/mergedResults.nf
  Script_1907e77ac7f65c51: /nfs/baldar/quanyiz/app/CRISPR_Pipeline/././processes/seqSpecCheck.nf
  Script_377d81b23bdea24f: /nfs/baldar/quanyiz/app/CRISPR_Pipeline/././processes/inference_perturbo.nf
  Script_db99707b24413321: /nfs/baldar/quanyiz/app/CRISPR_Pipeline/./mapping_guide_pipeline.nf
Dec-20 10:28:54.283 [main] DEBUG nextflow.Session - Session aborted -- Cause: Process `prepare_mapping_pipeline:downloadGenome` declares 2 input channels but 1 were specified
Dec-20 10:28:54.299 [main] DEBUG nextflow.Session - The following nodes are still active:
  [operator] collect
  [operator] collect
  [operator] collect
  [operator] collect

Dec-20 10:28:54.307 [Task monitor] DEBUG n.processor.TaskPollingMonitor - <<< barrier arrives (monitor: local) - terminating tasks monitor poll loop
Dec-20 10:28:54.307 [main] ERROR nextflow.cli.Launcher - Process `prepare_mapping_pipeline:downloadGenome` declares 2 input channels but 1 were specified
nextflow.exception.ScriptRuntimeException: Process `prepare_mapping_pipeline:downloadGenome` declares 2 input channels but 1 were specified
	at nextflow.script.ProcessDef.run(ProcessDef.groovy:174)
	at nextflow.script.BindableDef.invoke_a(BindableDef.groovy:51)
	at nextflow.script.ComponentDef.invoke_o(ComponentDef.groovy:40)
	at nextflow.script.WorkflowBinding.invokeMethod(WorkflowBinding.groovy:102)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeOnDelegationObjects(ClosureMetaClass.java:408)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:350)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:61)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at Script_13e5d248ad1ff388$_runScript_closure1$_closure2.doCall(Script_13e5d248ad1ff388:12)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1030)
	at groovy.lang.Closure.call(Closure.java:427)
	at groovy.lang.Closure.call(Closure.java:406)
	at nextflow.script.WorkflowDef.run0(WorkflowDef.groovy:204)
	at nextflow.script.WorkflowDef.run(WorkflowDef.groovy:188)
	at nextflow.script.BindableDef.invoke_a(BindableDef.groovy:51)
	at nextflow.script.ComponentDef.invoke_o(ComponentDef.groovy:40)
	at nextflow.script.WorkflowBinding.invokeMethod(WorkflowBinding.groovy:102)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeOnDelegationObjects(ClosureMetaClass.java:408)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:350)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:61)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:176)
	at Script_7a541110402dceee$_runScript_closure1$_closure2.doCall(Script_7a541110402dceee:24)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1030)
	at groovy.lang.Closure.call(Closure.java:427)
	at groovy.lang.Closure.call(Closure.java:406)
	at nextflow.script.WorkflowDef.run0(WorkflowDef.groovy:204)
	at nextflow.script.WorkflowDef.run(WorkflowDef.groovy:188)
	at nextflow.script.BindableDef.invoke_a(BindableDef.groovy:51)
	at nextflow.script.IterableDef$invoke_a.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at nextflow.script.BaseScript.run0(BaseScript.groovy:183)
	at nextflow.script.BaseScript.run(BaseScript.groovy:192)
	at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:236)
	at nextflow.script.ScriptRunner.run(ScriptRunner.groovy:242)
	at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:137)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:372)
	at nextflow.cli.Launcher.run(Launcher.groovy:500)
	at nextflow.cli.Launcher.main(Launcher.groovy:672)

**Comment by LucasSilvaFerreira** [comment]
@jiangsizhu1201  Can we work here to report and solve this problems

**Comment by jiangsizhu1201** [comment]
**1-4 solved.** I have corrected the scripts for issues 1, 2, and 4. For issue 3, I replaced the GitHub package with a conda package, so it should now work without any problems. 
As for issue 5, I haven’t encountered it—it should be using the same conda environment created earlier.

**Comment by jiangsizhu1201** [comment]
> > **1-4 solved.** I have corrected the scripts for issues 1, 2, and 4. For issue 3, I replaced the GitHub package with a conda package, so it should now work without any problems. As for issue 5, I haven’t encountered it—it should be using the same conda environment created earlier.
> 
> I found that the issue was due to a lack of configuration in input.config. To resolve it, I added the following lines:
> 
> ```
> withName:evaluation_plot { conda = './conda_envs/spec-file.txt' } 
> withName:evaluation_undefined_plot { conda = './conda_envs/spec-file.txt' }
> ```

Amazing! Thanks! I will add this back.

**Comment by zhaoshuoxp** [comment]
For #3, I found that gtfparse has several dependencies, and resolving compatibility issues with some of them can be quite difficult. So, I decided to revert to GTFProcessing. To ensure it works without needing manual installation of it, I added the following line: ```pip install git+https://github.com/LucasSilvaFerreira/GTFProcessing.git``` to line 20 in both processes/CreateMuData.nf and CreateMuData_HASHING.nf.
